### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by pc0124** [lmarena/copilot-arena#17]
CTRL + N is a basic keyboard shortcut for creating a new file, maybe find another combination. Also, it is not unknown to you that other ai copilot extensions exist, and now all of you are using the same shortcuts. I'm not sure how this should get fixed, or if this is a vscode problem, but I think it's an issue.

**Comment by waynchi** [comment]
Oh that's a good point... Let me change this to CTRL + 3

**Comment by waynchi** [comment]
Fixed!
