### ISSUE TITLE
VS code reloads every time terms are agreed to

### ISSUE THREAD

**Issue by matfat55** [lmarena/copilot-arena#9]
Every time i press agree or the x mark on the terms box that pops up on the side, my VS code just reloads and the box appears again. If you wait for it to go away the extension seems to not work.

**Comment by waynchi** [comment]
If you press agree / accept it should reload and the extension should work. If you press x, it reloads and prompts you again as you cannot use the extension without accepting the terms and conditions.

Are you accepting and still encountering this issue?

**Comment by matfat55** [comment]
Pressing agree would reload vscode and the dialog would appear again. I fixed it tho, I just made a new workspace and installed it.
